name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: add
      id: add
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: add
        setup-command: ''
        command: node add.js
        input: 1+1
        expected-output: '2'
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ADD_RESULTS: "${{steps.add.outputs.result}}"
      with:
        runners: add
